### ISSUE TITLE
Flexible layout solution

### ISSUE THREAD

**Issue by SunnyWMY** [jmeei/vue-formbuilder#2]
Can the form builder add elements(container, row and column) for a flexible layout? Is it possible to create a layout as the attached image? I really like your work! It's smart and simple. Thank you very much! [
![Form](https://user-images.githubusercontent.com/43843424/60634052-075ad680-9e40-11e9-91d0-a263561f6862.jpg)
](url)

**Comment by jmeei** [comment]
@sunny-ng Glad that you love this form builder! I pretty like the idea, however i am pretty occupied at the moment, so can't promise when this can be done.

**Comment by SunnyWMY** [comment]
@jmeei Thank you! I am looking forward to it~
