### ISSUE TITLE
Question: Does it support nesting?

### ISSUE THREAD

**Issue by pranavkumar389** [jmeei/vue-formbuilder#3]
Does this form builder support nesting of fields?

An option of a select field can have another select field and so on.
Example:-
There is a dropdown with two options 1. Day 2. Month.
If the user selects the option as Day, they will get another select box will appear with all the 7 Days.
And if the user selects the option as Month, they will get a select box will appear with all 12 months.

In this example, only one level of nesting, it can have multiple levels of nesting.

**Comment by jmeei** [comment]
Hi @pranavkumar389,

Currently this form builder not supporting it, but I will note it down and enhance it in future :)
